### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by andybak** [mattatz/unity-generative-tree#1]
Hi. I wanted to reuse ProceduralModelingBase and the associated editor class but it's not clear what licence you intend your code to be under. I'm hoping MIT or similar but it would be really useful if you could add a licence file of some kind.

(Great project by the way)

**Comment by SugoiDev** [comment]
Also interested in knowing this. I can't even peek at the code without a license.

**Comment by MostHated** [comment]
@mattatz 
I would like to know, too. : /

🥇

**Comment by ProgrammingLife** [comment]
So what about license? :)

**Comment by mattatz** [comment]
Excuse me everyone. I missed this issue thread :-(
I created MIT License 👍
